### ISSUE TITLE
Retreive test statistic

### ISSUE THREAD

**Issue by dakota-hawkins** [jessemzhang/tn_test#4]
Hi there! 

I've been playing around with `tn_test` in some of my work, and have been appreciating its approach for identifying cluster markers. I've been wanting to integrate it with Scanpy's `scanpy.tl.rank_genes_groups()` functionality, and was just wondering if there was a simple way to retrieve the test statistic?

Best,

Dakota

**Comment by jessemzhang** [comment]
Hey Dakota,


There's no function for grabbing it, but here's one thing you can do:


import numpy as np
from truncated_normal import truncated_normal as tn
muY, varY, muZ, varZ = tn.get_null_truncmv_params(a, b, muL, muR, var=var, ind=ind)
nY, nZ = len(y), len(z)
stat = (np.sum(z[:, ind])-np.sum(y[:, ind])-(nZ*muZ-nY*muY))/np.sqrt(nY*varY+nZ*varZ)


If you look in the get_p_val function in this file: https://github.com/jessemzhang/tn_test/blob/master/truncated_normal/truncated_normal.py, it'll show you the context. I think the easiest way to see what happens is just to copy/paste this file into your local directory, add a "print(stat)" to the get_p_val function.


Hope that's helpful. Happy Thanksgiving!


Best,
Jesse

--- original message ---
On November 12, 2020, 8:44 AM PST notifications@github.com wrote:



Hi there!

I've been playing around with tn_test in some of my work, and have been appreciating its approach for identifying cluster markers. I've been wanting to integrate it with Scanpy's scanpy.tl.rank_genes_groups() functionality, and was just wondering if there was a simple way to retrieve the test statistic?

Best,

Dakota

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by dakota-hawkins** [comment]
Hi Jesse! Thanks for the response -- and sorry for my slow response, just getting back to this project with some new data coming in. Very helpful and I'll definitely make use of it going forward!

Thanks again,

Dakota
